pollster/pages/urls.py
from django.contrib import admin
from django.urls import path
from pollster import urls
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('poll/',views.poll, name='poll'),
    path('contact/', views.contact, name='contact'),
    path('logout/', views.logoutUser, name='logout'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),

]

pollster/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

]

pollster/pollster/urls.py
from django.contrib import admin
from django.urls import include, path
admin.site.site_header = "BlueBell PollEasy Admin"
admin.site.site_title = "BlueBell PollEasy Admin Portal"
admin.site.index_title = "Welcome to BlueBell PollEasy Researcher Portal"

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

pollster/pages/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=122)
    email=models.EmailField()
    msg=models.TextField()
    date=models.DateField()
    def __str__(self):      
        return self.name

pollster/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollster/pages/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpRequest 
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login
from pages.models import Contact
from django.contrib import messages
from datetime import datetime

def index(request):
    if request.user.is_anonymous:
        return redirect('/signin')
    # messages.success(request, 'pallavi
    return render(request, 'home/index.html')
def poll(request):
  return render(request, 'pages/index.html')

def contact(request):
    if request.method=='POST':
        name=request.POST.get('name')
        email=request.POST.get('email')
        msg=request.POST.get('msg')
        contact=Contact(name=name,email=email,msg=msg, date=datetime.today())
        contact.save()
        messages.success(request, 'We will connect you! Thank you for connacting us!.')
    return render(request, 'home/contact.html')

def logoutUser(request):
    logout(request)
    return redirect('/signin')

def signup(request):
    if request.method=='POST':
        name=request.POST.get('username')
        firstname=request.POST.get('firstname')
        lastname=request.POST.get('lastname')
       
        email=request.POST.get('email')
        password=request.POST.get('password')
        confirmpassword=request.POST.get('confirmpassword')
        if not name.isalnum():
            messages.warning(request, 'Usernameshould contain')
            return redirect('/signup')
        if len(name)>10:
            messages.warning(request, 'Username must be under 10 charcter')
            return redirect('/signup')
        if password!=confirmpassword:
            messages.warning(request, 'Password do not match')
            return redirect('/signup')
        
        user = User.objects.create_user(username=name,email=email,password=password)
        user.first_name=firstname
        user.last_name=lastname
        user.save()
        messages.success(request, "Welcome to Bluebell Online Survey!")
        return redirect('/')

       
    return render(request, 'signup.html')

def signin(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        # check if user has entered correct credentials
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f"Welcome to Bluebell Online Survey!")
            return redirect("/")
        else:
            return render(request, 'sigin.html')
        
    return render(request, 'signin.html')

def about(request):
    return render(request, 'about.html')

pollster/polls/views.py
from django.http.response import Http404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm



from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
  try:
    question = Question.objects.get(pk=question_id)
  except Question.DoesNotExist:
    raise Http404("Question does not exist")
  return render(request, 'polls/detail.html', { 'question': question })

# Get question and display results
def results(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, 'polls/results.html', { 'question': question })

# Vote for a question choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


#register
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:login')
    else:
        form = UserCreationForm()
    return render(request, 'polls/register.html', {'form': form})


#login
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data= request.POST)
        if form.is_valid():
            return redirect('polls:index')
    else:
        form = AuthenticationForm()
    return render(request, 'polls/login.html', {'form': form})

def logout(request):
    
    return render(request, 'home/index.html')

pollster/templates/about.html
{% extends 'base1.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}About{% endblock title %}
    </title>
</head>

<body>
    {% block body %}
    <div class="container  my-5 justify-content-start">
        <h3 class="h3 text-center" id="aboutproject">Our Project</h3>
        <div class="row">
            <div class="col-md-6">
                SE Mini Project Based on Python. We have used Python Framework Django for creating this Bluebell
                website.
                We try to create Polling set.
                <br>
                We have used sqlite as a database
                <br>
                Html, Css and Javascript in the Frontend
                <br>
                A survey is a research method used for collecting data from a predefined group of respondents to gain
                information and insights into various topics of interest. ... The process involves asking people for
                information through a questionnaire, which can be either online or offline.
            </div>
            <div class=" offset-md-2 col-md-4 border">
                <img src="{% static 'report.jpg' %}" alt="" class='img-fluid img '>
                <a href="{% static 'ROLL NO.docx' %}"> <i class="fas fa-download download"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="container my-5">
        <h3 class="h3 text-center">Our Team</h3>
        <div class="row">
            <div class="col-md-2">
                <img src="{% static 'Pallavi.jpeg' %}" class="rounded float-start img-fluid img-thumbnail" height=95px
                    width=175px alt="...">

            </div>
            <div class="col-md-8">
                <h4>Pallavi Pandey</h4>
                <h4 class="h4">
                    Persuing BE in Information Technology. Her coding skills have a great hand in
                    enhancing the tools that our users use. With minute details taken care of her work helps other
                    members enhance their part as well as put this user's at ease.
                    </h3>
                    <div class="standard_social_links">
                        <div>
                            <!-- <li class="round-btn btn-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a>
    
                      </li> -->
                            <li class="round-btn btn-linkedin"><a href="#"><i class="fab fa-linkedin-in"
                                        aria-hidden="true"></i></a>

                            </li>
                            <!-- <li class="round-btn btn-twitter"><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a>
    
                      </li> -->
                            <li class="round-btn btn-instagram"><a href="#"><i class="fab fa-instagram"
                                        aria-hidden="true"></i></a>

                            </li>

                            <!-- <li class="round-btn btn-envelop"><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    
                      </li> -->
                        </div>
                    </div>
            </div>
        </div>
        <div class="row my-2">
            <div class="col-md-2">
                <img src="{% static 'Akanksha.jpeg' %}" class="rounded float-start img-fluid img-thumbnail" height=95px
                    width=175px alt="...">

            </div>
            <div class="col-md-8">
                <h4>Akansha Jhurani</h4>
                <h4 class="h4">
                    Persuing BE in Information Technology. Her command is at creating content and
                    handling the graphics part. She's the face that represents beautiful colours that are users see on
                    their screen.
                    </h3>
                    <div class="standard_social_links">
                        <div>
                            <!-- <li class="round-btn btn-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a>
    
                      </li> -->
                            <li class="round-btn btn-linkedin"><a href="#"><i class="fab fa-linkedin-in"
                                        aria-hidden="true"></i></a>

                            </li>
                            <!-- <li class="round-btn btn-twitter"><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a>
    
                      </li> -->
                            <li class="round-btn btn-instagram"><a href="#"><i class="fab fa-instagram"
                                        aria-hidden="true"></i></a>

                            </li>

                            <!-- <li class="round-btn btn-envelop"><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    
                      </li> -->
                        </div>
                    </div>
            </div>
        </div>
        <div class="row my-2">
            <div class="col-md-2">
                <img src="{% static 'Pratibha.jpeg' %}" class="rounded float-start img-fluid img-thumbnail" height=95px
                    width=175px alt="...">

            </div>
            <div class="col-md-8">
                <h4>Pratibha Prasad</h4>
                <h4 class="h4">
                    Persuing BE in Information Technology. Her skills to attain all the drawbacks
                    and check into what our user needs next is always handy when research is being made. All the
                    resources and results are being taken care by her
                    </h3>
                    <div class="standard_social_links">
                        <div>
                            <!-- <li class="round-btn btn-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a>
    
                      </li> -->
                            <li class="round-btn btn-linkedin"><a href="#"><i class="fab fa-linkedin-in"
                                        aria-hidden="true"></i></a>

                            </li>
                            <!-- <li class="round-btn btn-twitter"><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a>
    
                      </li> -->
                            <li class="round-btn btn-instagram"><a href="#"><i class="fab fa-instagram"
                                        aria-hidden="true"></i></a>

                            </li>

                            <!-- <li class="round-btn btn-envelop"><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a>
    
                      </li> -->
                        </div>
                    </div>
            </div>
        </div>
    </div>
    {% endblock body %}

</body>

</html>

pollster/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css">
  <script src="https://kit.fontawesome.com/158402db3c.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{%  static  'css/style.css'  %}">
  
  <title>BlueBell | PollEasy {% block title %}{% endblock %}</title>
</head>

<body>
  <!-- NavBar -->
  {% include 'partials/_navbar.html' %}


  <div class="landing">
    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>

</html>

pollster/templates/base1.html
{% load static %}
{% block base1 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>  {% block title%}{%endblock title%} |BlueBell
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Bluebell</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ms-auto pe-5 mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link " href="about">About</a>
                    </li>

                </ul>

            </div>
        </div>
    </nav>
    {% block body %}{% endblock body %}
</body>
</html>
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/fddf5c0916.js" crossorigin="anonymous"></script>
{% endblock base1 %}

pollster/templates/home/contact.html
{% extends 'navbar.html' %}
{% block body %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Contact Us{% endblock title %}</title>
    <link rel="stylesheet" type='text/css' href="{% static 'css/contact.css' %}">
     <link rel="stylesheet" href="../../static/css/contact.css">
</head>

 <body >
    <!-- <script src="../../static/contact.js"></script> -->

    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> -->
    <section >
        <div class="container">

            <h1 class="h2 text-center">Contact Us</h1>

            <form method='post' , action="/contact/" >
                {% csrf_token %}
                <div class="offset-md-1 col-md-10">




                    <div class="field name-box">
                        <input type="text" id="name" name="name" placeholder="Who Are You?" />
                        <label for="name">Name</label>
                        <span class="ss-icon">check</span>
                    </div>
                </div>
                <div class="offset-md-1 col-md-10">
                    <div class="field email-box">
                        <input type="text" id="email" name="email" placeholder="name@email.com" />
                        <label for="email">Email</label>
                        <span class="ss-icon">check</span>
                    </div>
                </div>

                <div class="offset-md-1 col-md-10">
                    <div class="field msg-box">
                        <input type="text" id="msg" name="msg" row="10" placeholder=" message..." />
                        <label for="msg">Msg</label>
                        <span class="ss-icon">check</span>
                    </div>
                </div>

                <div class="offset-md-1 col-md-10">
                    <input class="button" type="submit" value="Send" />
                </div>

            </form>




        </div>
    </section>
</body>

</html>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    // Input Lock
    $("textarea").blur(function () {
        $("#hire textarea").each(function () {
            $this = $(this);
            if (this.value != "") {
                $this.addClass("focused");
                $("textarea + label + span").css({ opacity: 1 });
            } else {
                $this.removeClass("focused");
                $("textarea + label + span").css({ opacity: 0 });
            }
        });
    });

    $("#hire .field:first-child input").blur(function () {
        $("#hire .field:first-child input").each(function () {
            $this = $(this);
            if (this.value != "") {
                $this.addClass("focused");
                $(".field:first-child input + label + span").css({ opacity: 1 });
            } else {
                $this.removeClass("focused");
                $(".field:first-child input + label + span").css({ opacity: 0 });
            }
        });
    });

    $("#hire .field:nth-child(2) input").blur(function () {
        $("#hire .field:nth-child(2) input").each(function () {
            $this = $(this);
            if (this.value != "") {
                $this.addClass("focused");
                $(".field:nth-child(2) input + label + span").css({ opacity: 1 });
            } else {
                $this.removeClass("focused");
                $(".field:nth-child(2) input + label + span").css({ opacity: 0 });
            }
        });
    });

</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script> 


{% endblock body %}

pollster/templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
<style>
  .card-body h1 {
    font-size: 3.2rem;
    color: white;
    font-weight: 400;
  }

  .card-body p {
    font-size: 1.6rem;
    color: white;
  }
</style>

<div class="card text-center">
  <div class="card-body">
    <h1>Welcome To BlueBell</h1>
    <p>Opinions Bring Revolution</p>
    <a class="btn btn-primary" href="{% url 'polls:login' %}">
      View Available Polls</a>
    <a href="/admin" class="btn btn-primary">Create Poll</a>
  </div>
</div>
{% endblock %}

pollster/templates/partials/_navbar.html
<style>
	.navbar-brand {
		display: block;

	}

	ul li a {
		text-decoration: none;
	}

	ul li i {
		font-size: 20px;
	}

	ul li {
		display: inline;
		margin: 0 5px;
	}

	p {
		color: white;

	}
</style>
<nav class="navbar navbar-dark bg-primary">
	<div class="container">
		<a class="navbar-brand" href="/">BlueBell PollEasy</a>

		<ul>

			<li> <a href="https://github.com/Pallavi679"><i style="color: rgb(163, 163, 163);"
						class="fab fa-github"></i></a> </li>
			<!-- <li> <a href="https://www.facebook.com/profile.php?id=100007950183884"><i style="color: rgb(15, 112, 177);"
						class="fab fa-facebook"></i></a></li> -->
			<li> <a href="https://www.instagram.com/pallavi6403/"> <i style="color:#ff8744bd"
						class="fab fa-instagram"></i></a></li>
			<!-- <li> <a href="https://twitter.com/Izrail03620970"> <i style="color: rgb(59, 146, 228);"
						class="fab fa-twitter"></i></a></li> -->
			<li> <a href="/"> <i style="color: rgb(59, 146, 228);"
						>Home</i></a></li>
			<!-- 
			{% if user.is_authenticated %}
			{% else %}
			<a href="{% url 'polls:login' %}" class="btn btn-primary">Login</a>
			<a href="{% url 'polls:register' %}" class="btn btn-primary">Register</a>

			{% endif %} -->




		</ul>

	</div>
</nav>

pollster/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<style>
	.landing {
  background: url(/static/images/1.jpg);
   min-height: 95vh;
   background-repeat: no-repeat;
    background-size: cover;
  }
  .bg-primary {
    background-color: #1b3652!important;
}
  .card-body
  {

    color:rgb(0, 0, 0);
    border: 1px solid rgba(0,0,0,.125);
    border-radius: .85rem;
    background: white;
    box-shadow: rgb(149 157 165 / 20%) 0px 8px 24px;
    padding: 30px;
    margin-bottom: 15px;
  }
  .card-body h1{
	font-size:2.5rem;
	color: black;
  }
  .card-body p
  {
	  font-size: 1.4rem;
	  color:rgb(0, 0, 0);
  }
 .btn-success
 {
	background: #353535;
 }
 .btn-success:hover
 {
	 background: rgb(14, 14, 26);
 }
  </style>
   <div class="card-body">
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back To Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %} 
	{% for choice in question.choice_set.all %}
		<div class="form-check">
			<input
				type="radio"
				name="choice"
				class="form-check-input"
				id="choice{{ forloop.counter }}"
				value="{{ choice.id }}"
			/>
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
			>
		</div>
	{% endfor %}
	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>
</div>
{% endblock %}

pollster/templates/polls/index.html
{% extends 'base.html' %} 
{% block content %} 

<style>
  
  .landing {
  background-image:url(/static/images/1.jpg);
   min-height: 95vh;
  }
  .bg-primary {
    background-color: #1b3652!important;
}
.btn-primary {
    color: #fff;
    background-color: #353535;
    border-color: #000000;
}
.card-body
{
  font-size: 1.4rem;
    color:rgb(0, 0, 0);
    border: 1px solid rgba(0,0,0,.125);
    border-radius: .85rem;
    background: white;
    box-shadow: rgb(149 157 165 / 20%) 0px 8px 24px;
    padding: 30px;
    margin-bottom: 15px;
}
 h1{
  font-size:2.5rem;
}
.card-body p
{
    font-size: 1.4rem;
    color:rgb(0, 0, 0);
}
</style>
  <h1 class="text-center mb-3">Poll Questions</h1>
  {% if latest_question_list %}
    {% for question in latest_question_list %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ question.question_text }}</p>
          <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
          <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available</p>
  {% endif %}
{% endblock %}

pollster/templates/polls/login.html
{% block content %}
<style>
    .bg-image {
        background-image: url(/static/images/1.jpg);
        filter: blur(4px);
        height: 101vh;
        width: 100wv;
        background-repeat: no-repeat;
        background-size: cover;
        margin: 0;
        padding: 0;
    }

    .login-form {

        box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .2);
        border-radius: 5px;
        background-color: rgba(255, 255, 255, .15);
        color: rgb(0, 0, 0);
        font-weight: bold;
        border-radius: 0.85rem;
        /* box-shadow: rgb(149 157 165 / 20%) 0px 8px 24px; */
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        z-index: 2;
        width: 35%;
        padding: 40px 20px;
        text-align: center;
    }

    h1 {
        margin-bottom: 42px;
    }

    .btn-primary {
        color: #fff;
        background-color: #15a000;
        border-color: #15a000;
        padding: 11px;
        border-radius: 6px;
    }

    .btn-blue {
        color: #fff;
        background-color: #147aff;
        border-color: #147aff;
        padding: 11px;
        border-radius: 6px;
    }

    a {
        text-decoration: none;
    }

    .user {

        font-size: 16px;
    }
</style>

<div class="bg-image"></div>
<div class="login-form">
    <h1>Login</h1>
    <form method="POST">

        {% csrf_token %}
        <div class="user">
            {{form.username.label}}
            <div style="width: 50px; height: 10px;" class="spacer"></div>
            {{form.username}}
            <br>
            <br>
            <br>
            <br>
            {{form.password.label}}
            <div style="width: 50px; height: 10px;" class="spacer"></div>
            {{form.password}}
            <br>
            <br>
            <br>
            <br>
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form> <br> <br>
    <h2>New to PollsEasy</h2>
    <a href="{% url 'polls:register' %}" class="btn btn-blue">Register</a>
</div>

{% endblock %}

pollster/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<style>
.landing {
  background: url(/static/images/1.jpg);
   min-height: 95vh;
   background-repeat: no-repeat;
    background-size: cover;
  }
  .bg-primary {
    background-color: #1b3652!important;
}
.card-body
  {
	
    color:rgb(0, 0, 0);
    border: 1px solid rgba(0,0,0,.125);
    border-radius: .85rem;
    background: white;
    box-shadow: rgb(149 157 165 / 20%) 0px 8px 24px;
    padding: 30px;
    margin-bottom: 15px;
  }
 .card-body  h1{
	font-size:2.5rem;
	color: black;
  }
  .card-body p
  {
	  font-size: 1.4rem;
	  color:rgb(0, 0, 0);
  }
  </style>
   <div class="card-body">
<h1 class="mb-5 text-center">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
	{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
	</li>
	{% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back To Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>
{% endblock %}